FROM ubuntu:latest

# Aktualisiere das System und installiere Python und pip
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y python3 python3-pip

# Erstelle einen Symlink für Python
RUN ln -sf python3 /usr/bin/python

# Erstelle den /app Ordner
RUN mkdir /app

# Kopiere requirements.txt
COPY requirements.txt /app
RUN pip3 install -r /app/requirements.txt --break-system-packages


# Kopiere die Dateien in den /app Ordner
COPY .env /app/.env
COPY sniffer.py /app/sniffer.py
COPY cicflowmeter /app/cicflowmeter
COPY adapt.py /app/adapt.py
COPY model.pkl /app
COPY scaler.pkl /app
COPY ipca_mit_size_34.pkl /app

# Nicht mehr verwendet
# COPY sshkey /app 
# COPY sshkey.pub /app


# Setze das Arbeitsverzeichnis auf /app
WORKDIR /app

# For debugging mostly
ENV AM_I_IN_A_DOCKER_CONTAINER=Yes
# Only Debugging! sendet alle Flows an den Server, nicht nur Anomalien!
ENV DEBUGGING=Yes

CMD ["/usr/bin/python3", "-u", "sniffer.py"]