FROM python:3.12-alpine

# Install necessary dependencies (Alpine version of tshark)
RUN apk update && apk add --no-cache \
    tshark \
    build-base \
    musl-dev \
    libffi-dev \
    gcc \
    g++ \
    make \
    libpcap-dev

# Create /app folder
RUN mkdir /app

# Copy requirements.txt
COPY requirements.txt /app

# Install Python packages from requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Symlink python3 to python
RUN ln -sf /usr/local/bin/python3 /usr/bin/python

# Copying the necessary files to working folder
COPY .env /app/.env
COPY sniffer.py /app/sniffer.py
COPY cicflowmeter /app/cicflowmeter
COPY pipelining_utilities.py /app/pipelining_utilities.py
COPY httpWriter.py /app/httpWriter.py
COPY model.pkl /app
COPY scaler.pkl /app
COPY ipca.pkl /app


WORKDIR /app

# For debugging mostly
ENV AM_I_IN_A_DOCKER_CONTAINER=Yes

CMD ["/usr/local/bin/python3", "-u", "sniffer.py"]