services:
  sensor:
    build:
      context: .
      dockerfile: DOCKERFILE
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW        
    restart: on-failure
    # folgendes stammt aus verschiedenen Tutorials hat aber keine Effekte gezeigt
    #privileged: true 
    #security_opt: 
    #  - seccomp:unconfined
    #cpus: 2
