FROM ubuntu:latest

# Aktualisiere das System und installiere Python und pip
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y python3 python3-pip
RUN apt-get install -y libpcap-dev

# Erstelle einen Symlink für Python
RUN ln -sf python3 /usr/bin/python

# Aktualisiere pip
# RUN pip3 install --force-reinstall --upgrade pip --break-system-packages

# Installiere Scapy und seine Abhängigkeiten
RUN pip3 install scapy --break-system-packages
RUN pip3 install numpy --break-system-packages
RUN pip3 install pandas --break-system-packages
RUN pip3 install scikit-learn --break-system-packages
RUN pip3 install python-dotenv --break-system-packages
RUN pip3 install paramiko imbalanced-learn --break-system-packages

# Erstelle den /app Ordner
RUN mkdir /app

# Kopiere die Dateien in den /app Ordner
COPY .env /app/.env
COPY sniffer.py /app/sniffer.py
COPY cicflowmeter /app/cicflowmeter
COPY adapt.py /app/adapt.py
COPY sshkey /app
COPY sshkey.pub /app
COPY model.pkl /app
COPY scaler.pkl /app
COPY ipca_mit_size_34.pkl /app

# Setze das Arbeitsverzeichnis auf /app
WORKDIR /app

# For debugging mostly
ENV AM_I_IN_A_DOCKER_CONTAINER=Yes

CMD ["/usr/bin/python3", "sniffer.py"]
