FROM python:3.12-alpine

# # Install necessary dependencies 
RUN apk --no-cache add procps  gcc g++ musl-dev python3-dev py3-scikit-learn openblas-dev

# Create /dash folder
RUN mkdir /dash

# Copy requirements.txt
COPY requirements.txt /dash

# Install Python packages from requirements.txt
RUN pip install --upgrade pip setuptools wheel
RUN pip install --no-cache-dir -r /dash/requirements.txt

# # Symlink python3 to python
RUN ln -sf /usr/local/bin/python3 /usr/bin/python

# Copying the necessary files to working folder
COPY .env /dash/.env
COPY run.py /dash/run.py
COPY instance /dash/instance
COPY app /dash/app


WORKDIR /dash

#CMD ["/usr/local/bin/python3", "-u", "run.py"] 
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "run:app", "-w 4", "--log-level=debug"]