FROM python:3.12-alpine

# # Install necessary dependencies 
RUN apk --no-cache add procps  gcc g++ musl-dev python3-dev py3-scikit-learn openblas-dev

# Create /dash folder
RUN mkdir /dash

# Copy requirements.txt
COPY requirements.txt /dash

# Install Python packages from requirements.txt
RUN pip install --upgrade pip setuptools wheel
RUN pip install --no-cache-dir -r /dash/requirements.txt

# # Symlink python3 to python
RUN ln -sf /usr/local/bin/python3 /usr/bin/python

# Copying the necessary files to working folder
COPY .env /dash/.env
COPY run.py /dash/run.py
# COPY instance /dash/instance # from docker-compose
COPY app /dash/app

WORKDIR /dash

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "1", "--threads", "1","--timeout", "0","--reload","--log-level=debug","--capture-output","--enable-stdio-inheritance","--access-logfile=-","--error-logfile=-","run:app"]